---
- name: Install dependencies for Redis
  apt: name={{ item }} state=present force=yes
  with_items:
    - build-essential
    - tcl8.5

- name: Add Chris Lea's PPA for Redis
  apt_repository: repo=ppa:chris-lea/redis-server state=present update_cache=true

- name: Install Redis
  apt: name={{ item }} state=present force=yes
  with_items:
    - redis-server
    - redis-client

- name: Copy configuration file
  template: src=roles/redis/templates/redis.conf.j2 dest=/etc/redis/redis.conf
  notify:
    - Restart Redis
