- hosts: web
  become: true
  become_method: sudo
  become_flags: -i
  vars:
    user: deploy
    sysctl:
      kernel:
        # Webserver
        shmmax: 8314667008
        shmall: 2029948

        # Vagrant, uncomment for testing purposes
        # shmmax: 1050267648 # 1GB
        # shmall: 256413

    # Let's Encrypt
    certbot_auto_renew_user: root
    certbot_auto_renew_minute: "0"
    certbot_auto_renew_hour: "5"
    certbot_auto_renew_options: --quiet --no-self-upgrade --nginx
    certbot_create_if_missing: true
    certbot_create_method: standalone
    certbot_admin_email: admin@otvorenesudy.sk
    certbot_certs:
      - email: admin@otvorenesudy.sk
        domains:
          - otvorenesudy.sk
          - api.otvorenesudy.sk
          - prokuratura.otvorenesudy.sk
    certbot_create_standalone_stop_services:
      - nginx
    certbot_install_from_source: false
    certbot_repo: https://github.com/certbot/certbot.git
    certbot_keep_updated: true
    certbot_create_command: "{{ certbot_script }} certonly --standalone --noninteractive --agree-tos --email {{ cert_item.email }} -d {{ cert_item.domains | join(',') }}"

  roles:
    - { role: system, tags: system }
    - { role: user, github_ssh_keys: [smolnar, pavolzbell], repositories: [otvorenesudy, otvorenesudy-api, otvorenesudy-prokuratura], tags: [user] }
    - { role: sysctl }
    - { role: iptables }
    - { role: logrotate }
    - {
        role: ruby,
        rubies:
          [
            { version: 2.3.8, bundler: 1.17.3 },
            { version: 2.5.0, bundler: 1.17.3 },
            { version: 2.7.3, bundler: 2.1.4 },
            { version: 3.3.0, bundler: 2.5.6 },
          ],
        tags: ruby,
      }
    - {
        role: postgresql,
        version: 16,
        users: [opencourts, opencourts_api, opencourts_prokuratura],
        tags: postgresql,
      }
    - { role: passenger-nginx, tags: nginx }
    - { role: elasticsearch, version: 1.7.6, tags: elasticsearch }
    - { role: redis, tags: redis }
    - { role: memcached, tags: memcached }
    - { role: letsencrypt, tags: [letsencrypt] }
    - { role: apps, tags: apps }
