- hosts: web
  become: true
  become_method: sudo
  vars:
    user: deploy
    sysctl:
      kernel:
        # Webserver
        shmmax: 12574642176 # 12GB of 24GB RAM in total
        shmall: 3069981

        # Vagrant, uncomment for testing purposes
        # shmmax: 1050267648 # 1GB
        # shmall: 256413
  roles:
    - { role: user, github_ssh_keys: [smolnar, pavolzbell] }
    - sysctl
    - iptables
    - logrotate
    - { role: ruby, rubies: [2.3.8, 2.5.0, 2.7.1] }
    - { role: postgresql, version: 9.5, users: [opencourts, opencourts_api, opencourts_prokuratura] }
    - passenger-nginx
    - { role: elasticsearch, version: 1.7.6 }
    - redis
    - memcached
