- name: Create deploy group
  group: name=deploy state=present

- name: Create application user
  user: name={{ user }} group=deploy shell=/bin/bash state=present

- name: Allow 'deploy' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%deploy'
    line: '%deploy ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Cleanup old keys
  file: path=/tmp/*.authorized_keys state=absent

- name: Setup exports file
  become_user: '{{ user }}'
  file:
    path: ~/.exports
    state: touch
    group: deploy
    mode: 0644

- name: Load exports file in .profile
  become_user: '{{ user }}'
  lineinfile:
    dest: ~/.profile
    line: source ~/.exports
    state: present

- name: Load exports file in .bashrc
  become_user: '{{ user }}'
  lineinfile:
    dest: ~/.bashrc
    line: source ~/.exports
    insertbefore: BOF
    state: present

- name: Copy the public keys from GitHub
  delegate_to: 127.0.0.1
  become: false
  get_url: url=https://github.com/{{item}}.keys dest=/tmp/{{item}}.authorized_keys
  with_items: '{{ github_ssh_keys }}'

- name: Install public keys
  authorized_key: user={{ user }} key={{ lookup('file', '/tmp/' + item + '.authorized_keys') }}
  with_items: '{{ github_ssh_keys }}'

- name: Create key for GitHub Actions
  become_user: '{{ user }}'
  openssh_keypair:
    path: "~/.ssh/github-actions"
    type: rsa
    size: 4096
    state: present
    force: no

- name: Print Github Actions public key
  become_user: '{{ user }}'
  command: cat ~/.ssh/github-actions.pub
  register: public_key
  changed_when: false

- name: Authorize GitHub Actions key
  become_user: '{{ user }}'
  authorized_key:
    user: '{{ user }}'
    state: present
    key: "{{ public_key.stdout }}"
   


