- name: Create deploy group
  group: name=deploy state=present

- name: Create application user
  user: name={{ user }} group=deploy shell=/bin/bash state=present

- name: Allow 'deploy' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%deploy'
    line: '%deploy ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Cleanup old keys
  file: path=/tmp/*.authorized_keys state=absent

- name: Setup global env file
  become_user: '{{ user }}'
  file:
    path: /home/{{ user }}/.env
    state: touch
    group: deploy
    mode: 0644

- name: Load env file in .profile
  become_user: '{{ user }}'
  lineinfile:
    dest: /home/{{ user }}/.profile
    line: export $(cat /home/{{ user }}/.env | xargs)
    insertbefore: EOF
    state: present

- name: Load global env file in .bashrc
  become_user: '{{ user }}'
  lineinfile:
    dest: /home/{{ user }}/.bashrc
    line: export $(cat /home/{{ user }}/.env | xargs)
    insertbefore: BOF
    state: present

- name: Copy the public keys from GitHub
  delegate_to: 127.0.0.1
  become: false
  get_url: url=https://github.com/{{item}}.keys dest=/tmp/{{item}}.authorized_keys
  with_items: '{{ github_ssh_keys }}'

- name: Install public keys
  authorized_key: user={{ user }} key={{ lookup('file', '/tmp/' + item + '.authorized_keys') }}
  with_items: '{{ github_ssh_keys }}'

- name: Create keys for GitHub Actions
  become_user: '{{ user }}'
  openssh_keypair:
    path: /home/{{ user }}/.ssh/github-actions-{{ item }}
    type: rsa
    size: 4096
    state: present
    force: no
  with_items: '{{ repositories }}'

- name: Add GitHub Actions keys to SSH config
  become_user: '{{ user }}'
  community.general.ssh_config:
    user: '{{ user }}'
    host: github.com-{{ item }}
    hostname: github.com
    identity_file: /home/{{ user }}/.ssh/github-actions-{{ item }}
    state: present
  with_items: '{{ repositories }}'

- name: Read GitHub Actions public keys
  slurp:
    src: /home/{{ user }}/.ssh/github-actions-{{ item }}.pub
  register: github_action_public_keys
  with_items: '{{ repositories }}'

- name: Add GitHub Actions public keys into Known Hosts
  authorized_key:
    user: '{{ user }}'
    key: "{{ item.content | b64decode }}"
  with_items: "{{ github_action_public_keys.results }}"


