- name: Create deploy group
  group: name=deploy state=present

- name: Create application user
  user: name={{ user }} group=deploy shell=/bin/bash state=present

- name: Cleanup old keys
  file: path=/tmp/*.authorized_keys state=absent

- name: Setup exports file
  become_user: '{{ user }}'
  file:
    path: ~/.exports
    state: touch
    group: deploy
    mode: 0644

- name: Load exports file in .profile
  become_user: '{{ user }}'
  lineinfile:
    dest: ~/.profile
    line: source ~/.exports
    state: present

- name: Load exports file in .bashrc
  become_user: '{{ user }}'
  lineinfile:
    dest: ~/.bashrc
    line: source ~/.exports
    insertbefore: BOF
    state: present

- name: Copy the public keys from Github
  delegate_to: 127.0.0.1
  sudo: no
  get_url: url=https://github.com/{{item}}.keys dest=/tmp/{{item}}.authorized_keys
  with_items: "{{ github_ssh_keys }}"

- name: Install public keys
  authorized_key: user={{ user }} key="{{ lookup('file', '/tmp/' + item + '.authorized_keys') }}"
  with_items: "{{ github_ssh_keys }}"
