- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
    update_cache: yes

- name: Install dependencies
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: latest
    update_cache: yes

- name: Install Node deb repositories
  shell: |
    mkdir -p /etc/apt/keyrings
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --yes --dearmor -o /etc/apt/keyrings/nodesource.gpg
    rm /etc/apt/sources.list.d/nodesource.list
    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list
    apt-get update

- name: Add NODE_OPTIONS to environment variables
  lineinfile:
    dest: "~/.env"
    regexp: "^NODE_OPTIONS="
    line: "NODE_OPTIONS=--openssl-legacy-provider"
    state: present
  become_user: "{{ user }}"

- name: Install a list of packages
  apt:
    pkg:
      - gcc
      - g++
      - dirmngr
      - gnupg
      - nodejs
      - libcurl4
      - libcurl4
      - libcurl4-openssl-dev
      - chromium-chromedriver
      - python3
      - python3-pip
      - python3-certbot-nginx
      - moreutils
      - ntp
      - unoconv
      - libpq-dev
      - libssl-dev
    update_cache: yes
    state: latest
    force: true

- name: Install yarn
  command: npm install --global yarn

- name: Create sda mounting point
  ansible.builtin.file:
    path: /mnt/sda
    state: directory
    mode: "0755"

- name: Create sdb mounting point
  ansible.builtin.file:
    path: /mnt/sdb
    state: directory
    mode: "0755"

- name: Create sdc mounting point
  ansible.builtin.file:
    path: /mnt/sdd
    state: directory
    mode: "0755"

- name: Copy /etc/fstab
  template: src=roles/system/templates/fstab dest=/etc/fstab
  notify:
    - Reload Mount All
