- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
    update_cache: yes

- name: Install Node deb repositories
  shell: curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -

- name: Install a list of packages
  apt:
    pkg:
      - gcc
      - g++
      - nodejs
      - dirmngr
      - gnupg
      - libcurl4-openssl-dev
      - chromium-chromedriver
      - python3-certbot-nginx
      - moreutils
    update_cache: yes
    state: latest
    force: true

- name: Install yarn
  command: npm install --global yarn
