- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
    update_cache: yes

- name: Install Node deb repositories
  shell: curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -

- name: Install a list of packages
  apt:
    pkg:
      - gcc
      - g++
      - nodejs
      - dirmngr
      - gnupg
      - libcurl4-openssl-dev
      - chromium-chromedriver
      - python3-certbot-nginx
      - moreutils
      - ntp
      - unoconv
    update_cache: yes
    state: latest
    force: true

- name: Install yarn
  command: npm install --global yarn

- name: Create sda mounting point
  ansible.builtin.file:
    path: /mnt/sda
    state: directory
    mode: "0755"

- name: Create sdb mounting point
  ansible.builtin.file:
    path: /mnt/sdb
    state: directory
    mode: "0755"

- name: Create sdc mounting point
  ansible.builtin.file:
    path: /mnt/sdd
    state: directory
    mode: "0755"

- name: Copy /etc/fstab
  template: src=roles/system/templates/fstab dest=/etc/fstab
  notify:
    - Reload Mount All
