- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
    update_cache: yes

- name: Install a list of packages
  apt:
    pkg:
      - gcc
      - g++
      - node
      - dirmngr
      - gnupg
      - libcurl4-openssl-dev
      - chromium-chromedriver
    update_cache: yes
    state: latest
    force: true

- name: Install yarn
  command: npm install --global yarn
