- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
    update_cache: yes

- name: Install latest Node repositories
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_17.x {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes

- name: Install a list of packages
  apt:
    pkg:
      - gcc
      - g++
      - nodejs
      - dirmngr
      - gnupg
      - libcurl4-openssl-dev
      - chromium-chromedriver
      - python3-certbot-nginx
    update_cache: yes
    state: latest
    force: true

- name: Install yarn
  command: npm install --global yarn
