---
- name: Add key for Passenger
  apt_key: keyserver=keyserver.ubuntu.com id=561F9B9CAC40B2F7 state=present

- name: Use apt via HTTPS
  apt:
    name:
      - apt-transport-https
      - ca-certificates
    state: present

- name: Add Passenger's apt repositories
  apt_repository: repo='deb https://oss-binaries.phusionpassenger.com/apt/passenger {{ansible_distribution_release}} main' state=present update_cache=yes

- name: Install Nginx
  apt:
    name:
      - libnginx-mod-http-passenger
      - nginx-full
      - nginx-extras
    state: present
    force: yes
    update_cache: true

- name: Check if /var/log/nginx is symlinked to /data
  stat:
    path: /var/log/nginx
  register: st

- name: Move and symlink /var/log/nginx to /data
  shell: |
    mv /var/log/nginx /data/var/log/nginx
    ln -s /data/var/log/nginx /var/log/nginx
  when: not st.stat.islnk
  notify:
    - Restart Nginx

- name: Link Passenger module
  file:
    src: /usr/share/nginx/modules-available/mod-http-passenger.load
    dest: /etc/nginx/modules-enabled/50-mod-http-passenger.conf
    state: link
    force: true

- name: Copy Nginx's configuration
  copy: src=roles/passenger-nginx/templates/nginx.conf dest=/etc/nginx/nginx.conf
  notify:
    - Restart Nginx

- name: Copy default page
  copy: src=roles/passenger-nginx/templates/default dest=/etc/nginx/sites-available/default

- name: Enable default page
  file: src=/etc/nginx/sites-available/default dest=/etc/nginx/sites-enabled/default state=link

- name: Copy default html page
  copy: src=roles/passenger-nginx/templates/index.html dest=/etc/nginx/index.html
  notify:
    - Restart Nginx

- name: Create application configuration
  template: src=roles/passenger-nginx/templates/{{ item.src }} dest=/etc/nginx/sites-available/{{ item.dest }}
  with_items:
    - { src: opencourts-api-production.j2, dest: opencourts-api-production }
    - { src: opencourts-production.j2, dest: opencourts-production }
    - { src: opencourts-prosecutors-production.j2, dest: opencourts-prosecutors-production }
    - { src: opencourts-prokuratura-production.j2, dest: opencourts-prokuratura-production }
  notify:
    - Restart Nginx

- name: Enable application configuration
  file: src=/etc/nginx/sites-available/{{ item }} dest=/etc/nginx/sites-enabled/{{ item }} state=link
  with_items:
    - opencourts-api-production
    - opencourts-production
    - opencourts-prosecutors-production
    - opencourts-prokuratura-production
  notify:
    - Restart Nginx
