- name: Copy self-recovery script
  copy: src=roles/apps/scripts/self-recovery.sh dest=/root/

- name: Run self-recovery script
  cron:
    name: "Trigger self-recovery check"
    minute: "*/10"
    job: /bin/bash /root/self-recovery.sh 2>> /root/self-recovery.log

- name: Copy elasticsearch-check script
  copy: src=roles/apps/scripts/elasticsearch-check.sh dest=/root/

- name: Run elasticsearch-check script
  cron:
    name: "Trigger elasticsearch-check check"
    minute: "*/1"
    job: /bin/bash /root/elasticsearch-check.sh 2>> /root/elasticsearch-check.log

- name: Copy Sidekiq restart script
  copy: src=roles/apps/scripts/sidekiq.sh dest=/home/deploy

- name: Trigger Sidekiq restart script
  cron:
    name: "Restart Sidekiq"
    hour: "*/24"
    user: deploy
    job: /bin/bash /home/deploy/sidekiq.sh 2>> /home/deploy/sidekiq.log

- name: Copy db-backup script
  copy: src=roles/apps/scripts/db-backup.sh dest=/root/

- name: Run db-backup script
  cron:
    name: "Trigger db-backup script"
    minute: "30"
    hour: "*/23"
    job: /bin/bash /root/db-backup.sh >> /root/db-backup.log
