---
- name: Add apt repository for Oracle Java 8
  apt_repository: repo='ppa:webupd8team/java'

- name: Accept Java 8 Licence
  become: yes
  shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | tee /etc/oracle-java-8-licence-acceptance | /usr/bin/debconf-set-selections
  args:
    creates: /etc/oracle-java-8-licence-acceptance

- name: Install Oracle Java 8
  become: yes
  apt:
    name:
      - oracle-java8-installer
      - ca-certificates
      - oracle-java8-set-default
    state: latest

- name: Check if Elasticsearch package is downloaded
  stat: path=/home/{{ user }}/elasticsearch-{{ version }}.deb
  register: st

- name: Fetch Elasticsearch package
  become: yes
  get_url: url=https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-{{ version }}.deb dest=/home/{{ user }}/ thirsty=yes mode=0440
  when: not st.stat.exists

- name: Install Elasticsearch package
  become: yes
  action: shell dpkg -i -E --force-confnew /home/{{ user }}/elasticsearch-{{ version }}.deb 2>&1 | grep skipping | wc -l

- name: Check if /var/lib/elasticsearch is symlinked to /data
  stat:
    path: /var/lib/elasticsearch
  register: st

- name: Move and symlink /var/lib/elasticsearch to /data
  shell: |
    mv /var/lib/elasticsearch /data/var/lib/elasticsearch
    ln -s /data/var/lib/elasticsearch /var/lib/elasticsearch
  when: not st.stat.islnk

- name: Copy Elasticsearch configuration
  copy: src=roles/elasticsearch/templates/elasticsearch.yml dest=/etc/elasticsearch/elasticsearch.yml
  notify:
    - Restart Elasticsearch

- name: Set ES_HEAP_SIZE variable for Elasticsearch
  lineinfile:
    dest: /etc/init.d/elasticsearch
    regexp: ^#?ES_HEAP_SIZE=.*
    line: ES_HEAP_SIZE={{ (sysctl.kernel.shmmax / 1000000000)|round|int }}g
  notify:
    - Restart Elasticsearch

- name: Set ES_JAVA_OPTS variable for Elasticsearch
  lineinfile:
    dest: /etc/init.d/elasticsearch
    regexp: ^#?ES_JAVA_OPTS=.*
    line: ES_JAVA_OPTS="-Xms{{ (sysctl.kernel.shmmax / 1000000000)|round|int }}g -Xmx{{ (sysctl.kernel.shmmax / 1000000000)|round|int }}g"
  notify:
    - Restart Elasticsearch

- name: Set MAX_LOCKED_MEMORY variable for Elasticsearch
  lineinfile:
    dest: /etc/init.d/elasticsearch
    regexp: ^#?MAX_LOCKED_MEMORY=.*
    line: MAX_LOCKED_MEMORY=unlimited
  notify:
    - Restart Elasticsearch

- name: Set CRON job to restart Elasticsearch every 8 hours
  cron:
    name: 'Restart Elasticsearch every 8 hours'
    hour: "6,14,22"
    job: service elasticsearch restart
