---
- name: Install memcached server
  apt:
    name:
      - memcached
    state: present
    update-cache: yes

- name: Install configuration file
  template: src=roles/memcached/templates/memcached.conf.j2 dest=/etc/memcached.conf
  notify:
    - Restart memcached
