---
- name: Install rbenv dependencies
  apt:
    name:
      - git-core
      - build-essential
      - libreadline-dev
      - libssl1.0-dev
      - libssl-dev
      - libyaml-dev
      - libxml2-dev
      - libxslt1-dev
      - zlib1g-dev
      - libffi-dev
    state: present

- name: Check if rbenv is already installed
  stat: path=/home/{{ user }}/.rbenv
  register: st

- name: Install rbenv
  become_user: '{{ user }}'
  git:
    repo: https://github.com/sstephenson/rbenv.git
    dest: /home/{{ user }}/.rbenv
    depth: 1
  when: not st.stat.exists

- name: Check if rbenv-build is already installed
  stat: path=/home/{{ user }}/.rbenv/plugins/ruby-build
  register: st

- name: Install ruby-build plugin
  become_user: '{{ user }}'
  git:
    repo: https://github.com/sstephenson/ruby-build.git
    dest: /home/{{ user }}/.rbenv/plugins/ruby-build
  when: not st.stat.exists

- name: Update ruby-build plugin
  become_user: '{{ user }}'
  command: chdir=/home/{{ user }}/.rbenv/plugins/ruby-build git pull

- name: Grant application user access to rbenv
  file: path=/home/{{ user }}/.rbenv group=deploy mode='g=rwx' recurse=yes

- name: Add rbenv to application user $PATH
  become_user: '{{ user }}'
  lineinfile:
    dest: ~/.profile
    line: export PATH="~/.rbenv/bin:$PATH"
    state: present

- name: Add gem options to ~/.gemrc
  become_user: '{{ user }}'
  lineinfile:
    dest: ~/.gemrc
    line: 'gem: --no-ri --no-rdoc'
    state: present
    create: true

- name: Initialize rbenv on login
  become_user: '{{ user }}'
  lineinfile:
    dest: ~/.profile
    line: eval "$(rbenv init -)"
    state: present

- name: Add Ubuntu Bionic security repository
  ansible.builtin.apt_repository:
    repo: deb http://security.ubuntu.com/ubuntu bionic-security main
    state: present

- name: Install OpenSSL 1.0 development dependencies to build Ruby 2.3.8
  apt:
    name:
      - libssl1.0-dev
    state: present

- name: Install Ruby 2.3.8
  command: sudo -iu {{ user }} rbenv install --skip-existing {{ rubies.0.version }}

- name: Install newest OpenSSL development dependencies
  apt:
    name:
      - libssl-dev
      - libcurl4-openssl-dev
    state: present

- name: Install all other Ruby versions
  command: sudo -iu {{ user }} rbenv install --skip-existing {{ item.version }}
  with_items: '{{ rubies }}'

- name: Set initial ruby
  command: sudo -iu {{ user }} rbenv global {{ rubies.1.version }}
  become_user: '{{ user }}'

- name: Install bundler
  shell: sudo -iu {{ user }} bash -c 'source .profile && rbenv shell {{ item.version }} && gem install bundler -v {{ item.bundler }}'
  with_items: '{{ rubies }}'
